name: Sick Jekyll Themes
url: http://katieball.me/jekyllthemes
description: Awesome themes by an Awesome chick

baseurl: /jekyllthemes

permalink: /themes/:title/

pygments: true
paginate: 10

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
